spring:
  sql:
    init:
       mode: never
       platform: postgresql
       continue-on-error: false
  jpa:
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/dboe
    username: test
    password: t3st
logging.level:
  org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG